# ===========================
# DB 설정
# ===========================
spring.datasource.url=jdbc:mysql://switchyard.proxy.rlwy.net:48785/railway?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=AUjyFJnHTFFlZHmOyPLIoZiKWqTzhSYO
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP 커넥션 풀
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.initialization-fail-timeout=10000

# ===========================
# JPA 설정
# ===========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.jpa.properties.hibernate.jdbc.fetch_size=50

# ===========================
# P6Spy 설정
# ===========================
# Spring Boot 4에서 적용 안 될 수 있어서 일단 비활성화
# decorator.datasource.p6spy.enable-logging=true
# decorator.datasource.p6spy.multiline=true
# decorator.datasource.p6spy.logging=slf4j

# ===========================
# JPA 디버그 / 통계
# ===========================
spring.jpa.properties.hibernate.generate_statistics=false

# ===========================
# 로깅
# ===========================
logging.level.org.hibernate.stat=OFF

# SQL 출력
logging.level.org.hibernate.SQL=DEBUG

# ? 파라미터 값 출력
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# 기존 Hibernate 타입 로그는 끔
logging.level.org.hibernate.type.descriptor.sql=OFF

# JPA 기본 로그
logging.level.org.springframework.orm.jpa=INFO

# P6Spy 로그 비활성화
logging.level.p6spy=OFF
logging.level.com.p6spy=OFF

# ===========================
# Jackson 설정
# ===========================
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non_null

# ===========================
# JWT 설정
# ===========================
jwt.secret=fitlog-secret-key-must-be-at-least-32-characters-long
# ===========================
# FatSecret API
# ===========================
fatsecret.client-id=1f5e1e14623343498ee0093b581eba54
fatsecret.client-secret=12175b5c61cd4d208a31c05a85645ab4
fatsecret.token-url=https://oauth.fatsecret.com/connect/token
fatsecret.api-url=https://platform.fatsecret.com/rest
